import { getAllCompanies } from '../../../../src/services/functions/Fmexicoreits'
import Ffetch from '../../../../src/services/Ffetch'

describe('MexcioREITS Service', () => {
  it('getAllCompanies: Should extract all companies from the request body', async () => {
    const downSpy = jest.spyOn(Ffetch, 'down')
    const html = `for(;;);({
  "errorsCode" : [ ],
  "response" : {
    "resultado" : [ {
      "idEmisora" : 31300,
      "idTpEmpresa" : 0,
      "claveEmisora" : "DANHOS",
      "razonSocial" : "BANCO NACIONAL DE MÉXICO, S.A.,  INTEGRANTE DEL GRUPO FINANCIERO BANAMEX",
      "direccion" : null,
      "telefono" : null,
      "fax" : null,
      "paginaWeb" : null,
      "rutaLogo" : null,
      "logoCotiza" : null,
      "fideicomitente" : null,
      "fechaConstitucion" : null,
      "prefijos" : null,
      "idSectorial" : 0,
      "fechaInscripcion" : null,
      "actividadEconomica" : null,
      "productosPrincipales" : null,
      "mail" : null,
      "historia" : null,
      "razonComercial" : null,
      "descripcion" : null,
      "serie" : null,
      "idEmision" : null,
      "descripciones" : null,
      "pais" : null,
      "idBolsa" : null,
      "bolsa" : null,
      "fideicomitentes" : null,
      "colonia" : null,
      "ciudad" : null,
      "cp" : null,
      "estado" : null,
      "tipoValor" : null,
      "isin" : null,
      "fechaListado" : null,
      "idBolsaOrigen" : null,
      "paisOrigen" : null,
      "idBolsaPrincipal" : null,
      "claveEmision" : null,
      "clasificacionEtf" : null,
      "regionEtf" : null,
      "idEstatusEmp" : null,
      "emision" : [ {
        "idEmision" : 328070,
        "idFormapago" : null,
        "idMoneda" : 1,
        "idEstatusemi" : 1,
        "idTpmercado" : null,
        "idSubtpvalor" : "1154",
        "idTpvalor" : "CF",
        "idPartxemp" : null,
        "cveSerie" : "13",
        "fechaEmision" : 1381294800000,
        "fechaCreacion" : 1381321698000,
        "creadoPor" : "mrobles",
        "monto" : 5980000000,
        "sistema" : "EVA",
        "impCirculacion" : 0,
        "operaBmv" : "S",
        "valEjercidos" : null,
        "operaCierre" : null,
        "autorizadoVc" : "1",
        "idTpedoperacion" : null,
        "cveEmision" : "DANHOS",
        "idBursatilidad" : "AL",
        "cveCorta" : null,
        "erogacionNeta" : null,
        "valNominal" : 0,
        "fechaPropagint" : null,
        "fechaUltaut" : null,
        "fechaVencto" : 2959131600000,
        "cuponVigente" : 0,
        "fechaModificacion" : 1654045139000,
        "modificadoPor" : "DSTG_VC",
        "fechaUltpagint" : null,
        "tasaNeta" : null,
        "tasaBruta" : null,
        "cveCupon" : null,
        "valInscritos" : 1509979065,
        "valCirculacion" : null,
        "precioEjercido" : 26,
        "prima" : null,
        "operaSentra" : null,
        "isin" : "MXCFDA020005",
        "factorVincula" : null,
        "tipoWarrant" : null,
        "precioValoresSubyacentes" : null,
        "calculaInteres" : null,
        "tipoLiquidacion" : null,
        "fechaAjuste" : null,
        "minimoEjercer" : null,
        "valorMoneda" : null,
        "porcentajeRendimientoLimitad" : null,
        "importeRendimientoLimitado" : null,
        "cobertura" : null,
        "fechaCnbv" : null,
        "folioCnbv" : "153/7441/2013",
        "inscritaRnv" : null,
        "porcentajePrimaRetornable" : null,
        "importePrimaRetornable" : null,
        "restricciones" : null,
        "desfaseDiasPeriodoCupon" : null,
        "emisora" : {
          "idEmpresa" : 31300,
          "razonSocial" : "BANCO NACIONAL DE MÉXICO, S.A.,  INTEGRANTE DEL GRUPO FINANCIERO BANAMEX",
          "rfc" : "BNM840515VB1",
          "fechaCreacion" : 1374680205000,
          "sistema" : "EMISNET",
          "creadoPor" : "bacomer1",
          "cveOperadora" : null,
          "operaBanxico" : null,
          "fechaInscBmv" : 1381294800000,
          "fechaInscRnv" : 1380603600000,
          "modificadoPor" : "oortiz",
          "fechaModificacion" : 1638371781000,
          "cveEmpresa" : null,
          "fechaConstitucion" : 1380776400000,
          "ejercicioSoc" : null,
          "numProtocol" : null,
          "actividadEconomica" : "BANCA Y CRÉDITO",
          "productosPrinc" : "SERVICIOS BANCARIOS",
          "nomCorto" : null,
          "cveEmisora" : "DANHOS",
          "capitalAcciones" : null,
          "capitalImporte" : null,
          "cveRuteo" : null,
          "fechaAutVc" : null,
          "fechaSusVc" : null,
          "oficioAut" : null,
          "oficioSus" : null,
          "pagaComision" : null,
          "operaPt" : null,
          "tipoLiquidacion" : null,
          "esProspecto" : 0
        },
        "datosEstadistica" : null,
        "estatus" : null,
        "descripcion" : null,
        "fideicomitente" : [ "CONCENTRADORA FIBRA DANHOS, S.A. DE C.V." ],
        "representante" : null,
        "idEmisora" : null
      } ],
      "listClasifSectorial" : null,
      "clasifSectorial" : null,
      "consejosAdministrativos" : null
    }, {
      "idEmisora" : 32989,
      "idTpEmpresa" : 0,
      "claveEmisora" : "EDUCA",
      "razonSocial" : "BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIPLE, INVEX GRUPO FINANCIERO",
      "direccion" : null,
      "telefono" : null,
      "fax" : null,
      "paginaWeb" : null,
      "rutaLogo" : null,
      "logoCotiza" : null,
      "fideicomitente" : null,
      "fechaConstitucion" : null,
      "prefijos" : null,
      "idSectorial" : 0,
      "fechaInscripcion" : null,
      "actividadEconomica" : null,
      "productosPrincipales" : null,
      "mail" : null,
      "historia" : null,
      "razonComercial" : null,
      "descripcion" : null,
      "serie" : null,
      "idEmision" : null,
      "descripciones" : null,
      "pais" : null,
      "idBolsa" : null,
      "bolsa" : null,
      "fideicomitentes" : null,
      "colonia" : null,
      "ciudad" : null,
      "cp" : null,
      "estado" : null,
      "tipoValor" : null,
      "isin" : null,
      "fechaListado" : null,
      "idBolsaOrigen" : null,
      "paisOrigen" : null,
      "idBolsaPrincipal" : null,
      "claveEmision" : null,
      "clasificacionEtf" : null,
      "regionEtf" : null,
      "idEstatusEmp" : null,
      "emision" : [ {
        "idEmision" : 383955,
        "idFormapago" : null,
        "idMoneda" : 1,
        "idEstatusemi" : 1,
        "idTpmercado" : null,
        "idSubtpvalor" : "1154",
        "idTpvalor" : "CF",
        "idPartxemp" : null,
        "cveSerie" : "18",
        "fechaEmision" : 1530075600000,
        "fechaCreacion" : 1530103828000,
        "creadoPor" : "cmoreno",
        "monto" : 9430000000,
        "sistema" : "EVA",
        "impCirculacion" : 9430000000,
        "operaBmv" : "S",
        "valEjercidos" : null,
        "operaCierre" : null,
        "autorizadoVc" : "1",
        "idTpedoperacion" : null,
        "cveEmision" : "EDUCA",
        "idBursatilidad" : "BA",
        "cveCorta" : null,
        "erogacionNeta" : null,
        "valNominal" : null,
        "fechaPropagint" : null,
        "fechaUltaut" : null,
        "fechaVencto" : null,
        "cuponVigente" : 0,
        "fechaModificacion" : 1654045139000,
        "modificadoPor" : "DSTG_VC",
        "fechaUltpagint" : null,
        "tasaNeta" : null,
        "tasaBruta" : null,
        "cveCupon" : null,
        "valInscritos" : 1227467453,
        "valCirculacion" : 471500000,
        "precioEjercido" : 20,
        "prima" : null,
        "operaSentra" : null,
        "isin" : "MXCFED090004",
        "factorVincula" : null,
        "tipoWarrant" : null,
        "precioValoresSubyacentes" : null,
        "calculaInteres" : null,
        "tipoLiquidacion" : null,
        "fechaAjuste" : null,
        "minimoEjercer" : null,
        "valorMoneda" : null,
        "porcentajeRendimientoLimitad" : null,
        "importeRendimientoLimitado" : null,
        "cobertura" : null,
        "fechaCnbv" : null,
        "folioCnbv" : "153/11954/2018",
        "inscritaRnv" : null,
        "porcentajePrimaRetornable" : null,
        "importePrimaRetornable" : null,
        "restricciones" : null,
        "desfaseDiasPeriodoCupon" : null,
        "emisora" : {
          "idEmpresa" : 32989,
          "razonSocial" : "BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIPLE, INVEX GRUPO FINANCIERO",
          "rfc" : "BIN940223KE0",
          "fechaCreacion" : 1510187922000,
          "sistema" : "EMISNET",
          "creadoPor" : "Punto1",
          "cveOperadora" : null,
          "operaBanxico" : null,
          "fechaInscBmv" : 1530075600000,
          "fechaInscRnv" : 1529902800000,
          "modificadoPor" : "Ticket#11108717",
          "fechaModificacion" : 1640192408000,
          "cveEmpresa" : null,
          "fechaConstitucion" : 1530075600000,
          "ejercicioSoc" : null,
          "numProtocol" : null,
          "actividadEconomica" : "BANCO",
          "productosPrinc" : "FINANCIEROS",
          "nomCorto" : null,
          "cveEmisora" : "EDUCA",
          "capitalAcciones" : null,
          "capitalImporte" : null,
          "cveRuteo" : null,
          "fechaAutVc" : null,
          "fechaSusVc" : null,
          "oficioAut" : null,
          "oficioSus" : null,
          "pagaComision" : null,
          "operaPt" : null,
          "tipoLiquidacion" : null,
          "esProspecto" : 0
        },
        "datosEstadistica" : null,
        "estatus" : null,
        "descripcion" : null,
        "fideicomitente" : null,
        "representante" : null,
        "idEmisora" : null
      } ],
      "listClasifSectorial" : null,
      "clasifSectorial" : null,
      "consejosAdministrativos" : null
    }, {
      "idEmisora" : 31811,
      "idTpEmpresa" : 0,
      "claveEmisora" : "FIBRAHD",
      "razonSocial" : "BANCO ACTINVER, S.A. INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO ACTINVER",
      "direccion" : null,
      "telefono" : null,
      "fax" : null,
      "paginaWeb" : null,
      "rutaLogo" : null,
      "logoCotiza" : null,
      "fideicomitente" : null,
      "fechaConstitucion" : null,
      "prefijos" : null,
      "idSectorial" : 0,
      "fechaInscripcion" : null,
      "actividadEconomica" : null,
      "productosPrincipales" : null,
      "mail" : null,
      "historia" : null,
      "razonComercial" : null,
      "descripcion" : null,
      "serie" : null,
      "idEmision" : null,
      "descripciones" : null,
      "pais" : null,
      "idBolsa" : null,
      "bolsa" : null,
      "fideicomitentes" : null,
      "colonia" : null,
      "ciudad" : null,
      "cp" : null,
      "estado" : null,
      "tipoValor" : null,
      "isin" : null,
      "fechaListado" : null,
      "idBolsaOrigen" : null,
      "paisOrigen" : null,
      "idBolsaPrincipal" : null,
      "claveEmision" : null,
      "clasificacionEtf" : null,
      "regionEtf" : null,
      "idEstatusEmp" : null,
      "emision" : [ {
        "idEmision" : 344253,
        "idFormapago" : null,
        "idMoneda" : 1,
        "idEstatusemi" : 1,
        "idTpmercado" : null,
        "idSubtpvalor" : "1154",
        "idTpvalor" : "CF",
        "idPartxemp" : null,
        "cveSerie" : "15",
        "fechaEmision" : 1433912400000,
        "fechaCreacion" : 1433939542000,
        "creadoPor" : "ngonzalez",
        "monto" : 1500750000,
        "sistema" : "EVA",
        "impCirculacion" : 1500750000,
        "operaBmv" : "S",
        "valEjercidos" : null,
        "operaCierre" : null,
        "autorizadoVc" : "1",
        "idTpedoperacion" : null,
        "cveEmision" : "FIBRAHD",
        "idBursatilidad" : "MI",
        "cveCorta" : null,
        "erogacionNeta" : null,
        "valNominal" : 0,
        "fechaPropagint" : null,
        "fechaUltaut" : null,
        "fechaVencto" : null,
        "cuponVigente" : 0,
        "fechaModificacion" : 1654045139000,
        "modificadoPor" : "DSTG_VC",
        "fechaUltpagint" : null,
        "tasaNeta" : null,
        "tasaBruta" : null,
        "cveCupon" : null,
        "valInscritos" : 437179992,
        "valCirculacion" : 150075000,
        "precioEjercido" : 10,
        "prima" : null,
        "operaSentra" : null,
        "isin" : "MXCFFI1H0008",
        "factorVincula" : null,
        "tipoWarrant" : null,
        "precioValoresSubyacentes" : null,
        "calculaInteres" : null,
        "tipoLiquidacion" : null,
        "fechaAjuste" : null,
        "minimoEjercer" : null,
        "valorMoneda" : null,
        "porcentajeRendimientoLimitad" : null,
        "importeRendimientoLimitado" : null,
        "cobertura" : null,
        "fechaCnbv" : null,
        "folioCnbv" : "153/5375/2015",
        "inscritaRnv" : null,
        "porcentajePrimaRetornable" : null,
        "importePrimaRetornable" : null,
        "restricciones" : null,
        "desfaseDiasPeriodoCupon" : null,
        "emisora" : {
          "idEmpresa" : 31811,
          "razonSocial" : "BANCO ACTINVER, S.A. INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO ACTINVER",
          "rfc" : "PBI061115SC6",
          "fechaCreacion" : 1421430412000,
          "sistema" : "EMISNET",
          "creadoPor" : "actinver",
          "cveOperadora" : null,
          "operaBanxico" : null,
          "fechaInscBmv" : 1433912400000,
          "fechaInscRnv" : 1433480400000,
          "modificadoPor" : "Ticket#11108717",
          "fechaModificacion" : 1642693860000,
          "cveEmpresa" : null,
          "fechaConstitucion" : 1433912400000,
          "ejercicioSoc" : null,
          "numProtocol" : null,
          "actividadEconomica" : "SERVICIOS FIDUCIARIOS ",
          "productosPrinc" : "FINANCIEROS",
          "nomCorto" : null,
          "cveEmisora" : "FIBRAHD",
          "capitalAcciones" : null,
          "capitalImporte" : null,
          "cveRuteo" : null,
          "fechaAutVc" : null,
          "fechaSusVc" : null,
          "oficioAut" : null,
          "oficioSus" : null,
          "pagaComision" : null,
          "operaPt" : null,
          "tipoLiquidacion" : null,
          "esProspecto" : 0
        },
        "datosEstadistica" : null,
        "estatus" : null,
        "descripcion" : null,
        "fideicomitente" : [ "ACTINVER CASA DE BOLSA, S.A. DE C.V., GRUPO FINANCIERO ACTINVER, DIVISIÓN FIDUCIARIA" ],
        "representante" : null,
        "idEmisora" : null
      } ],
      "listClasifSectorial" : null,
      "clasifSectorial" : null,
      "consejosAdministrativos" : null
    }, {
      "idEmisora" : 30066,
      "idTpEmpresa" : 0,
      "claveEmisora" : "TERRA",
      "razonSocial" : "CIBANCO,S.A. INSTITUCION DE BANCA MULTIPLE",
      "direccion" : null,
      "telefono" : null,
      "fax" : null,
      "paginaWeb" : null,
      "rutaLogo" : null,
      "logoCotiza" : null,
      "fideicomitente" : null,
      "fechaConstitucion" : null,
      "prefijos" : null,
      "idSectorial" : 0,
      "fechaInscripcion" : null,
      "actividadEconomica" : null,
      "productosPrincipales" : null,
      "mail" : null,
      "historia" : null,
      "razonComercial" : null,
      "descripcion" : null,
      "serie" : null,
      "idEmision" : null,
      "descripciones" : null,
      "pais" : null,
      "idBolsa" : null,
      "bolsa" : null,
      "fideicomitentes" : null,
      "colonia" : null,
      "ciudad" : null,
      "cp" : null,
      "estado" : null,
      "tipoValor" : null,
      "isin" : null,
      "fechaListado" : null,
      "idBolsaOrigen" : null,
      "paisOrigen" : null,
      "idBolsaPrincipal" : null,
      "claveEmision" : null,
      "clasificacionEtf" : null,
      "regionEtf" : null,
      "idEstatusEmp" : null,
      "emision" : [ {
        "idEmision" : 270662,
        "idFormapago" : null,
        "idMoneda" : 1,
        "idEstatusemi" : 1,
        "idTpmercado" : null,
        "idSubtpvalor" : "1154",
        "idTpvalor" : "CF",
        "idPartxemp" : null,
        "cveSerie" : "13",
        "fechaEmision" : 1363759200000,
        "fechaCreacion" : 1363791134000,
        "creadoPor" : "rhernandez",
        "monto" : 4480000000,
        "sistema" : "EVA",
        "impCirculacion" : 0,
        "operaBmv" : "S",
        "valEjercidos" : null,
        "operaCierre" : null,
        "autorizadoVc" : "1",
        "idTpedoperacion" : null,
        "cveEmision" : "TERRA",
        "idBursatilidad" : "AL",
        "cveCorta" : null,
        "erogacionNeta" : null,
        "valNominal" : 0,
        "fechaPropagint" : null,
        "fechaUltaut" : null,
        "fechaVencto" : 4519432800000,
        "cuponVigente" : 0,
        "fechaModificacion" : 1655333759000,
        "modificadoPor" : "evelasco",
        "fechaUltpagint" : null,
        "tasaNeta" : null,
        "tasaBruta" : null,
        "cveCupon" : null,
        "valInscritos" : 777842964,
        "valCirculacion" : null,
        "precioEjercido" : 28,
        "prima" : null,
        "operaSentra" : null,
        "isin" : "MXCFTE0B0005",
        "factorVincula" : null,
        "tipoWarrant" : null,
        "precioValoresSubyacentes" : null,
        "calculaInteres" : null,
        "tipoLiquidacion" : null,
        "fechaAjuste" : null,
        "minimoEjercer" : null,
        "valorMoneda" : null,
        "porcentajeRendimientoLimitad" : null,
        "importeRendimientoLimitado" : null,
        "cobertura" : null,
        "fechaCnbv" : null,
        "folioCnbv" : "153/6497/2013",
        "inscritaRnv" : null,
        "porcentajePrimaRetornable" : null,
        "importePrimaRetornable" : null,
        "restricciones" : null,
        "desfaseDiasPeriodoCupon" : null,
        "emisora" : {
          "idEmpresa" : 30066,
          "razonSocial" : "CIBANCO,S.A. INSTITUCION DE BANCA MULTIPLE",
          "rfc" : "BNY080206UR9",
          "fechaCreacion" : 1352700000000,
          "sistema" : "EMISNET",
          "creadoPor" : "banamex01",
          "cveOperadora" : null,
          "operaBanxico" : null,
          "fechaInscBmv" : 1363759200000,
          "fechaInscRnv" : 1363327200000,
          "modificadoPor" : "lcuatepotzo",
          "fechaModificacion" : 1640885816000,
          "cveEmpresa" : null,
          "fechaConstitucion" : 1362463200000,
          "ejercicioSoc" : null,
          "numProtocol" : null,
          "actividadEconomica" : "LA PRESTACIÓN DEL SERVICIO DE BANCA Y CRÉDITO EN TÉRMINOS DE LA LEY DE INSTITUCIONES DE CRÉDITO Y REALIZARÁ OPERACIONES Y PRESTAR SERVICIOS BANCARIOS A QUE SE REFIERE EL ARTÍCULO 46 DE DICHA LEY",
          "productosPrinc" : "SERVICIOS DE BANCA Y CRÉDITO",
          "nomCorto" : null,
          "cveEmisora" : "TERRA",
          "capitalAcciones" : null,
          "capitalImporte" : null,
          "cveRuteo" : null,
          "fechaAutVc" : null,
          "fechaSusVc" : null,
          "oficioAut" : null,
          "oficioSus" : null,
          "pagaComision" : null,
          "operaPt" : null,
          "tipoLiquidacion" : null,
          "esProspecto" : 0
        },
        "datosEstadistica" : null,
        "estatus" : null,
        "descripcion" : null,
        "fideicomitente" : [ "PLA ADMINISTRADORA INDUSTRIAL, S. DE R.L. DE C.V." ],
        "representante" : null,
        "idEmisora" : null
      } ],
      "listClasifSectorial" : null,
      "clasifSectorial" : null,
      "consejosAdministrativos" : null
    } ]
  },
  "success" : true
})`
    downSpy.mockResolvedValue(html)
    const companies = await getAllCompanies('general', 1)
    expect(companies).toEqual([
      {
        claveEmisora: 'DANHOS',
        idEmisora: 31300,
        idTpEmpresa: 0,
        mainUrl: 'https://www.bmv.com.mx/es/emisoras/perfil/-31300',
        razonComercial: null,
        razonSocial: 'BANCO NACIONAL DE MÉXICO, S.A.,  INTEGRANTE DEL GRUPO FINANCIERO BANAMEX',
      },
      {
        claveEmisora: 'EDUCA',
        idEmisora: 32989,
        idTpEmpresa: 0,
        mainUrl: 'https://www.bmv.com.mx/es/emisoras/perfil/-32989',
        razonComercial: null,
        razonSocial: 'BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIPLE, INVEX GRUPO FINANCIERO',
      },
      {
        claveEmisora: 'FIBRAHD',
        idEmisora: 31811,
        idTpEmpresa: 0,
        mainUrl: 'https://www.bmv.com.mx/es/emisoras/perfil/-31811',
        razonComercial: null,
        razonSocial: 'BANCO ACTINVER, S.A. INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO ACTINVER',
      },
      {
        claveEmisora: 'TERRA',
        idEmisora: 30066,
        idTpEmpresa: 0,
        mainUrl: 'https://www.bmv.com.mx/es/emisoras/perfil/-30066',
        razonComercial: null,
        razonSocial: 'CIBANCO,S.A. INSTITUCION DE BANCA MULTIPLE',
      },
    ])
    expect(downSpy).toHaveBeenCalledTimes(1)
    downSpy.mockRestore()
  })
})
